function [pathstring] = make_relative_path(rel_path_tree,path_1)
% Reconstructs the relative path from path_1 using the relative
% path tree generated by find_relative_path
tmpdir=cd;
pathstring=path_1;
for v=1:length(rel_path_tree)
    cd([pathstring filesep rel_path_tree{v}]);
    pathstring=cd;
end
cd(tmpdir);
